Repository udoprog/fixed-map, pull requests merged in 2022-10, with the labels that each got.

#7 Remove unsafety with soon-to-be stable GATs
  .github/workflows/ci.yml
  Cargo.toml
  README.md
  README.tpl
  fixed-map-derive/src/lib.rs
  src/key.rs
  src/map.rs
  src/set.rs
  src/storage.rs
  src/storage/boolean.rs
  src/storage/map.rs
  src/storage/option.rs
  src/storage/singleton.rs
Labels: enhancement

#8 Inline more and introduce map feature
  Cargo.toml
  README.md
  src/key.rs
  src/lib.rs
  src/map.rs
  src/set.rs
  src/storage.rs
  src/storage/boolean.rs
  src/storage/map.rs
  src/storage/option.rs
  src/storage/singleton.rs
Labels: enhancement

#12 Implement `IntoIterator` and `FromIterator` for Map and Set
  fixed-map-derive/src/lib.rs
  src/map.rs
  src/set.rs
  src/storage.rs
  src/storage/boolean.rs
  src/storage/map.rs
  src/storage/option.rs
  src/storage/singleton.rs
  tests/derive_tests.rs
Labels: enhancement

#13 Forbid unsafe, edition 2021, MSRV 1.65, more lints
  .github/workflows/ci.yml
  Cargo.toml
  README.md
  fixed-map-derive/src/lib.rs
  src/lib.rs
  src/map.rs
  src/set.rs
  src/storage.rs
  src/storage/boolean.rs
  src/storage/map.rs
  src/storage/option.rs
  src/storage/singleton.rs
Labels: enhancement

#16 Forbid unsafe, fix lints, check more in CI
  .github/workflows/ci.yml
  fixed-map-derive/src/lib.rs
  src/lib.rs
Labels: enhancement

#17 Fix broken Eq impl and move more things to doc tests
  fixed-map-derive/src/lib.rs
  src/map.rs
  src/set.rs
  tests/derive_tests.rs
Labels: bug, enhancement

#18 Add more iterators and more tests
  benches/map_benches.rs
  fixed-map-derive/src/any_variants.rs
  fixed-map-derive/src/context.rs
  fixed-map-derive/src/lib.rs
  fixed-map-derive/src/unit_variants.rs
  src/map.rs
  src/set.rs
  src/storage.rs
  src/storage/boolean.rs
  src/storage/map.rs
  src/storage/option.rs
  src/storage/singleton.rs
Labels: enhancement

#19 More implementation through Storage and DoubleEndedIterator
  examples/empty.rs
  fixed-map-derive/src/any_variants.rs
  fixed-map-derive/src/context.rs
  fixed-map-derive/src/lib.rs
  fixed-map-derive/src/unit_variants.rs
  src/key.rs
  src/lib.rs
  src/macros.rs
  src/map.rs
  src/set.rs
  src/storage.rs
  src/storage/boolean.rs
  src/storage/map.rs
  src/storage/option.rs
  src/storage/singleton.rs
Labels: enhancement

#22 impl `Map::contains_key`
  fixed-map-derive/src/any_variants.rs
  fixed-map-derive/src/unit_variants.rs
  src/map.rs
  src/set.rs
  src/storage.rs
  src/storage/boolean.rs
  src/storage/map.rs
  src/storage/option.rs
  src/storage/singleton.rs
Labels: enhancement

#20 run clippy for all features, tests, examples, etc
  .github/workflows/ci.yml
  src/map.rs
  src/set.rs
Labels: enhancement

#23 Solve performance of values iterators
  benches/complex.rs
  benches/simple.rs
  fixed-map-derive/src/any_variants.rs
  fixed-map-derive/src/context.rs
  fixed-map-derive/src/unit_variants.rs
  src/key.rs
  src/lib.rs
  src/macros.rs
  src/map.rs
  src/set.rs
  src/storage/option.rs
Labels: enhancement

#24 Add more documentation for Key and update benchmarks
  README.md
  fixed-map-derive/src/any_variants.rs
  src/key.rs
  src/lib.rs
Labels: bug, enhancement

#25 Improve documentation
  README.md
  src/lib.rs
  src/map.rs
  src/set.rs
Labels: enhancement

#26 Use core iterators for most storage
  src/storage/boolean.rs
  src/storage/option.rs
  src/storage/singleton.rs
Labels: enhancement

#28 Make last couple of map iterators forwarding impls
  fixed-map-derive/src/any_variants.rs
  fixed-map-derive/src/unit_variants.rs
  src/storage/map.rs
Labels: enhancement

#30 Add Peter Jaszkowiak as author
  Cargo.toml
Labels: enhancement

#31 Entry API
  .github/workflows/ci.yml
  .gitignore
  Cargo.toml
  README.md
  fixed-map-derive/Cargo.toml
  fixed-map-derive/src/any_variants.rs
  fixed-map-derive/src/context.rs
  fixed-map-derive/src/lib.rs
  fixed-map-derive/src/unit_variants.rs
  src/lib.rs
  src/map.rs
  src/storage.rs
  src/storage/boolean.rs
  src/storage/entry.rs
  src/storage/entry/boolean.rs
  src/storage/entry/map.rs
  src/storage/entry/option.rs
  src/storage/entry/option_bucket.rs
  src/storage/entry/singleton.rs
  src/storage/map.rs
  src/storage/option.rs
  src/storage/singleton.rs
  tests/entry.rs
Labels: enhancement

#32 Style nits and rework the entry traits
  fixed-map-derive/src/any_variants.rs
  fixed-map-derive/src/context.rs
  fixed-map-derive/src/unit_variants.rs
  src/lib.rs
  src/map.rs
  src/option_bucket.rs
  src/option_bucket/tests.rs
  src/storage/boolean.rs
  src/storage/entry.rs
  src/storage/entry/boolean.rs
  src/storage/entry/map.rs
  src/storage/entry/option.rs
  src/storage/entry/singleton.rs
  src/storage/map.rs
  src/storage/option.rs
  src/storage/singleton.rs
Labels: enhancement

#33 Introduce entry benchmarks
  benches/complex.rs
Labels: enhancement

#37 Add some forwarding impls Hash, Ord, PartialOrd
  fixed-map-derive/src/any_variants.rs
  fixed-map-derive/src/context.rs
  fixed-map-derive/src/lib.rs
  fixed-map-derive/src/unit_variants.rs
  src/map.rs
  src/set.rs
Labels: enhancement

#39 Fix ordering in the least bad way possible maybe (fixes #38)
  fixed-map-derive/src/context.rs
  fixed-map-derive/src/unit_variants.rs
  src/key.rs
  src/lib.rs
  src/macro_support.rs
  src/map.rs
  src/set.rs
Labels: bug

#40 Remove entry feature
  Cargo.toml
  fixed-map-derive/Cargo.toml
  fixed-map-derive/src/any_variants.rs
  fixed-map-derive/src/context.rs
  fixed-map-derive/src/unit_variants.rs
  src/key.rs
  src/lib.rs
  src/map.rs
  src/map/entry.rs
  src/map/storage.rs
  src/map/storage/boolean.rs
  src/map/storage/map.rs
  src/map/storage/option.rs
  src/map/storage/singleton.rs
  src/option_bucket.rs
  src/set.rs
  src/storage.rs
  src/storage/entry/boolean.rs
  src/storage/entry/map.rs
  src/storage/entry/option.rs
  src/storage/entry/singleton.rs
  tests/entry.rs
Labels: enhancement

#41 Introduce SetStorage and clean up derives
  .github/workflows/ci.yml
  Cargo.toml
  benches/complex.rs
  examples/composite.rs
  fixed-map-derive/Cargo.toml
  fixed-map-derive/src/any_variants.rs
  fixed-map-derive/src/context.rs
  fixed-map-derive/src/unit_variants.rs
  src/key.rs
  src/lib.rs
  src/macro_support.rs
  src/map.rs
  src/map/entry.rs
  src/map/storage.rs
  src/map/storage/boolean.rs
  src/map/storage/hashbrown.rs
  src/map/storage/option.rs
  src/map/storage/singleton.rs
  src/set.rs
  src/set/storage.rs
  src/set/storage/boolean.rs
  src/set/storage/hashbrown.rs
  src/set/storage/option.rs
  src/set/storage/singleton.rs
  tests/entry.rs
  tests/map_feature.rs
Labels: enhancement
